# Generated by Django 5.2.6 on 2025-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__standard', 'student__roll_number']},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name', 'section']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['standard__name', 'roll_number']},
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('standard', 'roll_number')},
        ),
    ]
