# Generated by Django 5.2.6 on 2025-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__roll_number']},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2, unique=True),
        ),
    ]
